[tool.poetry]
name = "observing-scenarios-simulations"
version = "0.0.0"
description = "LIGO/Virgo/KAGRA observing scenarios simulations"
authors = ["Leo Singer <leo.singer@ligo.org>"]

[tool.poetry.dependencies]
astropy = "^4.1"
astroplan = {git = "https://github.com/astropy/astroplan"}  # https://github.com/astropy/astroplan/issues/479
python = "^3.6.1"
scipy = "*"
seaborn = "*"
"ligo.skymap" = "^0.5.0"
"scikits.bootstrap" = "*"
gwpy = "*"
ipykernel = "*"
ipython = "*"
ipywidgets = "*"
gracedb-sdk = "*"
lxml = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
